version: "3.4"
services:
  ids:
    build: 
      context: ./ids
      network: host
    depends_on:
      - db

  db: 
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: "no"
    environment: 
      MYSQL_DATABASE: "traffic"
      MYSQL_USER: "user" 
      MYSQL_PASSWORD: "password" 
      MYSQL_ROOT_PASSWORD: "root" 
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e 'SELECT * FROM packets;' traffic
