version: "3.4"
services:
  ids:
    build: 
      context: ./ids
      network: host
    depends_on:
      - db

  frontend: 
    build: frontend
    ports:
      - 8080:80
    depends_on:
      - db
      - backend

  backend: 
    build: backend
    depends_on:
      - db

  db: 
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: "no"
    environment: 
      MYSQL_DATABASE: "traffic"
      MYSQL_USER: "user" 
      MYSQL_PASSWORD: "password" 
      MYSQL_ROOT_PASSWORD: "root" 
    healthcheck:
      test: mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e 'SELECT 1'
      interval: 10s
      timeout: 10s
      retries: 30

