version: "3.4"
services:

  frontend: 
    build: frontend
    ports:
      - 8080:80
    depends_on:
      - db
      - backend
    links:
      - db
      - backend

  backend: 
    build: backend
    ports:
      - 9000:9000
    depends_on:
      - db
    links:
      - db

  db: 
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: "no"
    environment: 
      MYSQL_DATABASE: "interests"
      MYSQL_USER: "user" 
      MYSQL_PASSWORD: "password" 
      MYSQL_ROOT_PASSWORD: "root" 
    healthcheck:
      test: mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e 'SELECT 1'
      interval: 10s
      timeout: 10s
      retries: 30

